[core] Add doxygen doc for Math namespace.
STORM-IRIT/Radium-Engine pull request #1030
Opened 2022-12-13 18:44 UTC by dlyr

currently, function in math namespace are not documented.
this is due to the fact that math namespace misses documentation.

this PR adds a small doc to math namespace such that every documented function in math namespace get their documentation available in doxygen

before
![Screenshot from 2022-12-13 19-42-45](https://user-images.githubusercontent.com/11328509/207418381-1d4cf73c-7bfb-41a5-970d-ace45b55b05d.png)
after 
![Screenshot from 2022-12-13 19-41-58](https://user-images.githubusercontent.com/11328509/207418408-64518dcf-ee42-4c12-997f-e23a0b17dd18.png)

![Screenshot from 2022-12-13 19-42-16](https://user-images.githubusercontent.com/11328509/207418437-7d5abc9d-d7b1-4109-8427-ad1f42236058.png)

2022-12-13 20:47 UTC, nmellado approved these changes

2022-12-13 20:57 UTC, MathiasPaulin requested changes
Need to discuss about that AFK.

2022-12-14 14:41 UTC, MathiasPaulin approved these changes

2022-12-14 14:54 UTC, nmellado commented
We wait for version update before merging.

2022-12-14 17:45 UTC, merged